esphome:
  name: nodemcucellar
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "Some"
  password: "Wifi"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Nodemcucellar Fallback Hotspot"
    password: "aGNy1pw8UcXF"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "pass123"

ota:
  password: "pass123"
  
time:
  - platform: homeassistant
    id: esptime

sensor:
  - platform: homeassistant
    id: dht_temp
    entity_id: sensor.esp_cellar_temperature
    internal: true

  - platform: homeassistant
    id: dht_hum
    entity_id: sensor.esp_cellar_humidity
    internal: true
    
  - platform: dht
    pin: 2
    temperature:
      name: "esp-cellar-temperature"
      id: dht_temp1
      accuracy_decimals: 1
      force_update: yes
    humidity:
      name: "esp-cellar-humidity"
      id: dht_hum1
      accuracy_decimals: 1
      force_update: yes

    update_interval: 60s
    model: DHT11

font:
  - file: 'slkscr.ttf'
    id: font1
    size: 10

  - file: 'BebasNeue-Regular.ttf'
    id: font2
    size: 48

  - file: 'arial.ttf'
    id: font3
    size: 14

i2c:
  sda: D1
  scl: D2
  scan: True

display:
  - platform: ssd1306_i2c
    model: "SH1106 128x64"
    reset_pin: D0
    address: 0x3C
    lambda: |-
      // Print "Text" in top center.
      it.printf(64, 0, id(font1), TextAlign::TOP_CENTER, "Cellar-sensor");

      // Print time in HH:MM format
      it.strftime(0, 60, id(font2), TextAlign::BASELINE_LEFT, "%H:%M", id(esptime).now());

      // Print DHT Temperature (from homeassistant sensor)
      if (id(inside_temperature).has_state()) {
        it.printf(127, 23, id(font3), TextAlign::TOP_RIGHT , "%.1f°", id(dht_temp1).state);
      }

      // Print DHT Humidity (from homeassistant sensor)
      if (id(outside_temperature).has_state()) {
        it.printf(127, 60, id(font3), TextAlign::BASELINE_RIGHT , "%.1f%%", id(dht_hum1).state);
      }
      
